name: Docker build

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4

            - name: Docker login
              run: docker login -u ${{ secrets.DOCKER_USER }} -p "${{ secrets.DOCKER_PASSWORD }}"

            - name: Construir imagen
              run: docker build -t juanfr97/node-test:latest .

            - name: Publicar en Docker Hub
              run: docker push juanfr97/node-test:latest